INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'The Hitchhiker''s Guide to the Galaxy', 2005, TRUE, 'https://www.rottentomatoes.com/m/hitchhikers_guide_to_the_galaxy', 60);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'The Endless', 2017, FALSE, 'https://www.rottentomatoes.com/m/the_endless', 92);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Timecrimes', 2007, TRUE, 'https://www.rottentomatoes.com/m/time_crimes', 90);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Ad Astra', 2019, TRUE, 'https://www.rottentomatoes.com/m/ad_astra', 83);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Westworld', 1973, FALSE, 'https://www.rottentomatoes.com/m/westworld', 84);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'High Life', 2018, FALSE, 'https://www.rottentomatoes.com/m/high_life_2019', 82);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Coherence', 2013, FALSE, 'https://www.rottentomatoes.com/m/coherence_2013', 89);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'The Rocky Horror Picture Show', 1975, FALSE, 'https://www.rottentomatoes.com/m/rocky_horror_picture_show', 79);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Midnight Special', 2016, TRUE, 'https://www.rottentomatoes.com/m/midnight_special_2015', 83);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Wizards', 1977, FALSE, 'https://www.rottentomatoes.com/m/wizards', 62);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Annihilation', 2018, TRUE, 'https://www.rottentomatoes.com/m/annihilation', 88);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Contact', 1997, FALSE, 'https://www.rottentomatoes.com/m/1078021-contact', 68);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'The Congress', 2013, FALSE, 'https://www.rottentomatoes.com/m/the_congress', 73);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Flight of the Navigator', 1986, FALSE, 'https://www.rottentomatoes.com/m/flight_of_the_navigator', 84);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Little Shop of Horrors', 1986, FALSE, 'https://www.rottentomatoes.com/m/1012515-little_shop_of_horrors', 91);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Alita: Battle Angel', 2019, TRUE, 'https://www.rottentomatoes.com/m/alita_battle_angel', 62);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Ready Player One', 2018, TRUE, 'https://www.rottentomatoes.com/m/ready_player_one', 72);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Plan 9 From Outer Space', 1959, FALSE, 'https://www.rottentomatoes.com/m/plan-9-from-outer-space', 66);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Rollerball', 1975, FALSE, 'https://www.rottentomatoes.com/m/rollerball', 67);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Silent Running', 1972, FALSE, 'https://www.rottentomatoes.com/m/silent_running', 71);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'War of the Worlds', 2005, TRUE, 'https://www.rottentomatoes.com/m/war_of_the_worlds', 76);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Metropolis', 2001, FALSE, 'https://www.rottentomatoes.com/m/metropolis_2002', 87);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Shin Godzilla', 2016, FALSE, 'https://www.rottentomatoes.com/m/godzilla_resurgence', 86);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Star Trek III: The Search for Spock', 1984, TRUE, 'https://www.rottentomatoes.com/m/star_trek_iii_the_search_for_spock', 78);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Rogue One: A Star Wars Story', 2016, TRUE, 'https://www.rottentomatoes.com/m/rogue_one_a_star_wars_story', 84);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'The Fountain', 2006, FALSE, 'https://www.rottentomatoes.com/m/the_fountain', 53);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Logan''s Run', 1976, FALSE, 'https://www.rottentomatoes.com/m/logans_run', 60);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'The Blob', 1958, FALSE, 'https://www.rottentomatoes.com/m/the_blob', 68);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Scanners', 1981, FALSE, 'https://www.rottentomatoes.com/m/1018315-scanners', 68);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Things to Come', 1936, FALSE, 'https://www.rottentomatoes.com/m/things_to_come', 91);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Cube', 1997, FALSE, 'https://www.rottentomatoes.com/m/cube', 63);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Strange Days', 1995, TRUE, 'https://www.rottentomatoes.com/m/strange_days', 68);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Heavy Metal', 1981, FALSE, 'https://www.rottentomatoes.com/m/1068461-heavy_metal', 66);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'A Boy and His Dog', 1975, FALSE, 'https://www.rottentomatoes.com/m/boy_and_his_dog', 78);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'A.I.: Artificial Intelligence', 2001, TRUE, 'https://www.rottentomatoes.com/m/ai_artificial_intelligence', 76);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'The Day of the Triffids', 1963, FALSE, 'https://www.rottentomatoes.com/m/the_day_of_the_triffids_1963', 78);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'When Worlds Collide', 1951, FALSE, 'https://www.rottentomatoes.com/m/when_worlds_collide', 81);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Sunshine', 2007, TRUE, 'https://www.rottentomatoes.com/m/sunshine', 76);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Liquid Sky', 1982, FALSE, 'https://www.rottentomatoes.com/m/liquid_sky', 93);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Dark Star', 1974, FALSE, 'https://www.rottentomatoes.com/m/dark_star', 74);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Open Your Eyes', 1997, FALSE, 'https://www.rottentomatoes.com/m/open_your_eyes_1999', 87);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Paprika', 2006, TRUE, 'https://www.rottentomatoes.com/m/paprika', 86);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Serenity', 2005, TRUE, 'https://www.rottentomatoes.com/m/serenity', 82);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Turbo Kid', 2015, FALSE, 'https://www.rottentomatoes.com/m/turbo_kid', 91);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'THX-1138', 1971, FALSE, 'https://www.rottentomatoes.com/m/thx_1138', 86);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Attack the Block', 2011, TRUE, 'https://www.rottentomatoes.com/m/attack_the_block', 91);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Upgrade', 2018, FALSE, 'https://www.rottentomatoes.com/m/upgrade_2018', 88);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Star Trek: First Contact', 1996, FALSE, 'https://www.rottentomatoes.com/m/star_trek_first_contact', 93);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'The World''s End', 2013, TRUE, 'https://www.rottentomatoes.com/m/the_worlds_end', 89);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Invasion of the Body Snatchers', 1978, FALSE, 'https://www.rottentomatoes.com/m/1010679-invasion_of_the_body_snatchers', 93);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'The Host', 2006, TRUE, 'https://www.rottentomatoes.com/m/the_host_2007', 93);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'A Quiet Place', 2018, FALSE, 'https://www.rottentomatoes.com/m/a_quiet_place_2018', 96);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Star Wars: The Force Awakens', 2015, TRUE, 'https://www.rottentomatoes.com/m/star_wars_episode_vii_the_force_awakens', 93);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Repo Man', 1984, TRUE, 'https://www.rottentomatoes.com/m/repo_man', 98);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Starship Troopers', 1997, TRUE, 'https://www.rottentomatoes.com/m/starship_troopers', 72);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'The Fifth Element', 1997, TRUE, 'https://www.rottentomatoes.com/m/fifth_element', 71);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'V for Vendetta', 2006, TRUE, 'https://www.rottentomatoes.com/m/v_for_vendetta', 73);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Dredd', 2012, TRUE, 'https://www.rottentomatoes.com/m/dredd', 80);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'The Brother From Another Planet', 1984, FALSE, 'https://www.rottentomatoes.com/m/the_brother_from_another_planet', 89);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'The Adventures of Buckaroo Banzai Across the Eighth Dimension', 1984, FALSE, 'https://www.rottentomatoes.com/m/the_adventures_of_buckaroo_banzai', 66);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Dark City', 1998, TRUE, 'https://www.rottentomatoes.com/m/dark_city', 76);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Under the Skin', 2013, FALSE, 'https://www.rottentomatoes.com/m/under_the_skin_2013', 84);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'The Man Who Fell to Earth', 1976, FALSE, 'https://www.rottentomatoes.com/m/man_who_fell_to_earth', 80);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'The Fly', 1986, FALSE, 'https://www.rottentomatoes.com/m/1007602-fly', 93);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Cloverfield', 2008, TRUE, 'https://www.rottentomatoes.com/m/cloverfield', 78);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Men in Black', 1997, TRUE, 'https://www.rottentomatoes.com/m/men_in_black', 91);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Tron', 1982, TRUE, 'https://www.rottentomatoes.com/m/tron', 73);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Bumblebee', 2018, TRUE, 'https://www.rottentomatoes.com/m/bumblebee', 91);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Independence Day', 1996, TRUE, 'https://www.rottentomatoes.com/m/1071806-independence_day', 68);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Barbarella', 1968, FALSE, 'https://www.rottentomatoes.com/m/barbarella', 75);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Donnie Darko', 2001, TRUE, 'https://www.rottentomatoes.com/m/donnie_darko', 87);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Pacific Rim', 2013, TRUE, 'https://www.rottentomatoes.com/m/pacific_rim_2013', 72);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Idiocracy', 2006, TRUE, 'https://www.rottentomatoes.com/m/idiocracy', 71);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Fahrenheit 451', 1966, FALSE, 'https://www.rottentomatoes.com/m/1007003-fahrenheit_451', 81);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Demolition Man', 1993, FALSE, 'https://www.rottentomatoes.com/m/demolition_man', 62);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'A Scanner Darkly', 2006, TRUE, 'https://www.rottentomatoes.com/m/scanner_darkly', 68);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Source Code', 2011, TRUE, 'https://www.rottentomatoes.com/m/source_code', 92);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'The Abyss', 1989, FALSE, 'https://www.rottentomatoes.com/m/abyss', 88);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Rise of the Planet of the Apes', 2011, TRUE, 'https://www.rottentomatoes.com/m/rise_of_the_planet_of_the_apes', 82);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Altered States', 1980, FALSE, 'https://www.rottentomatoes.com/m/altered_states', 85);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Predestination', 2014, TRUE, 'https://www.rottentomatoes.com/m/predestination', 84);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'They Live', 1988, TRUE, 'https://www.rottentomatoes.com/m/they_live', 86);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Seconds', 1966, FALSE, 'https://www.rottentomatoes.com/m/seconds', 79);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Soylent Green', 1973, FALSE, 'https://www.rottentomatoes.com/m/soylent_green', 72);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, '20,000 Leagues Under the Sea', 1954, TRUE, 'https://www.rottentomatoes.com/m/1000079-20000_leagues_under_the_sea', 90);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'The Hunger Games', 2012, TRUE, 'https://www.rottentomatoes.com/m/the_hunger_games', 84);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Avatar', 2009, TRUE, 'https://www.rottentomatoes.com/m/avatar', 81);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Minority Report', 2002, TRUE, 'https://www.rottentomatoes.com/m/minority_report', 89);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Alphaville', 1965, FALSE, 'https://www.rottentomatoes.com/m/alphaville', 92);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Them!', 1954, FALSE, 'https://www.rottentomatoes.com/m/1021186-them', 93);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Videodrome', 1983, FALSE, 'https://www.rottentomatoes.com/m/videodrome', 83);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Snowpiercer', 2013, TRUE, 'https://www.rottentomatoes.com/m/snowpiercer', 94);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Invasion of the Body Snatchers', 1956, FALSE, 'https://www.rottentomatoes.com/m/1010678-invasion_of_the_body_snatchers', 98);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Predator', 1987, FALSE, 'https://www.rottentomatoes.com/m/predator', 80);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Planet of the Apes', 1968, TRUE, 'https://www.rottentomatoes.com/m/1016397-planet_of_the_apes', 87);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Mad Max 2: The Road Warrior', 1981, TRUE, 'https://www.rottentomatoes.com/m/mad_max_2_the_road_warrior', 93);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Star Trek', 2009, TRUE, 'https://www.rottentomatoes.com/m/star_trek_11', 94);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Escape From New York', 1981, FALSE, 'https://www.rottentomatoes.com/m/1006717-escape_from_new_york', 88);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'The War of the Worlds', 1953, FALSE, 'https://www.rottentomatoes.com/m/the_war_of_the_worlds', 89);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Blade Runner 2049', 2017, TRUE, 'https://www.rottentomatoes.com/m/blade_runner_2049', 88);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Galaxy Quest', 1999, TRUE, 'https://www.rottentomatoes.com/m/galaxy_quest', 90);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Fantastic Voyage', 1966, FALSE, 'https://www.rottentomatoes.com/m/fantastic_voyage', 92);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Solaris', 1972, TRUE, 'https://www.rottentomatoes.com/m/solaris_1976', 92);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Her', 2013, TRUE, 'https://www.rottentomatoes.com/m/her', 94);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'The Iron Giant', 1999, TRUE, 'https://www.rottentomatoes.com/m/iron_giant', 96);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Fantastic Planet', 1973, TRUE, 'https://www.rottentomatoes.com/m/fantastic_planet', 91);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Total Recall', 1990, TRUE, 'https://www.rottentomatoes.com/m/total_recall', 82);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Moon', 2009, TRUE, 'https://www.rottentomatoes.com/m/moon', 90);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'The Martian', 2015, TRUE, 'https://www.rottentomatoes.com/m/the_martian', 91);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Gravity', 2013, TRUE, 'https://www.rottentomatoes.com/m/gravity_2013', 96);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Interstellar', 2014, TRUE, 'https://www.rottentomatoes.com/m/interstellar_2014', 73);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Eternal Sunshine of the Spotless Mind', 2004, TRUE, 'https://www.rottentomatoes.com/m/eternal_sunshine_of_the_spotless_mind', 92);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Looper', 2012, TRUE, 'https://www.rottentomatoes.com/m/looper', 93);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Close Encounters of the Third Kind', 1977, TRUE, 'https://www.rottentomatoes.com/m/close_encounters_of_the_third_kind', 94);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Arrival', 2016, TRUE, 'https://www.rottentomatoes.com/m/arrival_2016', 94);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Ex Machina', 2014, TRUE, 'https://www.rottentomatoes.com/m/ex_machina', 92);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'WALL-E', 2008, TRUE, 'https://www.rottentomatoes.com/m/wall_e', 95);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'E.T. the Extra-Terrestrial', 1982, FALSE, 'https://www.rottentomatoes.com/m/et_the_extraterrestrial', 99);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Godzilla', 1954, FALSE, 'https://www.rottentomatoes.com/m/godzilla_1956', 93);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Forbidden Planet', 1956, FALSE, 'https://www.rottentomatoes.com/m/forbidden_planet', 96);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, '12 Monkeys', 1995, FALSE, 'https://www.rottentomatoes.com/m/12_monkeys', 88);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Jurassic Park', 1993, FALSE, 'https://www.rottentomatoes.com/m/jurassic_park', 91);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Primer', 2004, TRUE, 'https://www.rottentomatoes.com/m/primer', 73);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Stalker', 1979, FALSE, 'https://www.rottentomatoes.com/m/1043378-stalker', 10);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Gattaca', 1997, TRUE, 'https://www.rottentomatoes.com/m/gattaca', 82);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Ghost in the Shell', 1995, TRUE, 'https://www.rottentomatoes.com/m/ghost_in_the_shell', 95);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Brazil', 1985, TRUE, 'https://www.rottentomatoes.com/m/1003033-brazil', 98);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Star Trek II: The Wrath of Khan', 1982, TRUE, 'https://www.rottentomatoes.com/m/star_trek_ii_the_wrath_of_khan', 87);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'District 9', 2009, TRUE, 'https://www.rottentomatoes.com/m/district_9', 90);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'A Clockwork Orange', 1971, TRUE, 'https://www.rottentomatoes.com/m/clockwork_orange', 87);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'RoboCop', 1987, TRUE, 'https://www.rottentomatoes.com/m/1017712-robocop', 92);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'The Day the Earth Stood Still', 1951, FALSE, 'https://www.rottentomatoes.com/m/1005371-day_the_earth_stood_still', 95);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Akira', 1988, TRUE, 'https://www.rottentomatoes.com/m/akira', 91);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Children of Men', 2006, TRUE, 'https://www.rottentomatoes.com/m/children_of_men', 92);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'The Terminator', 1984, TRUE, 'https://www.rottentomatoes.com/m/terminator', 10);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Edge of Tomorrow', 2014, TRUE, 'https://www.rottentomatoes.com/m/live_die_repeat_edge_of_tomorrow', 91);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Aliens', 1986, TRUE, 'https://www.rottentomatoes.com/m/1000617-aliens', 98);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Star Wars: Episode V -- The Empire Strikes Back', 1980, TRUE, 'https://www.rottentomatoes.com/m/star_wars_the_empire_strikes_back', 94);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'The Thing', 1982, TRUE, 'https://www.rottentomatoes.com/m/1021244-thing', 85);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Mad Max: Fury Road', 2015, TRUE, 'https://www.rottentomatoes.com/m/mad_max_fury_road', 97);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Alien', 1979, TRUE, 'https://www.rottentomatoes.com/m/alien', 93);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Terminator 2: Judgment Day', 1991, TRUE, 'https://www.rottentomatoes.com/m/terminator_2_judgment_day', 91);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Inception', 2010, TRUE, 'https://www.rottentomatoes.com/m/inception', 87);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'The Matrix', 1999, TRUE, 'https://www.rottentomatoes.com/m/matrix', 83);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Star Wars: Episode IV -- A New Hope', 1977, TRUE, 'https://www.rottentomatoes.com/m/star_wars_a_new_hope', 93);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Metropolis', 1927, TRUE, 'https://www.rottentomatoes.com/m/1013775-metropolis', 97);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Blade Runner', 1982, TRUE, 'https://www.rottentomatoes.com/m/blade_runner', 88);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Back to the Future', 1985, TRUE, 'https://www.rottentomatoes.com/m/back_to_the_future', 93);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, '2001: A Space Odyssey', 1968, TRUE, 'https://www.rottentomatoes.com/m/2001_a_space_odyssey', 92);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Star Wars: Episode V - The Empire Strikes Back', 1980, FALSE, 'https://www.rottentomatoes.com/m/star_wars_episode_v_the_empire_strikes_back', 95);
INSERT INTO "PUBLIC"."MOVIE" VALUES(default, 'Star Wars: Episode IV - A New Hope', 1977, FALSE, 'https://www.rottentomatoes.com/m/star_wars_episode_iv_a_new_hope', 93);
