INSERT INTO "PUBLIC"."MOVIE" VALUES(1, 'The Hitchhiker''s Guide to the Galaxy', 2005, TRUE, 'https://www.rottentomatoes.com/m/hitchhikers_guide_to_the_galaxy', 60);
INSERT INTO "PUBLIC"."MOVIE" VALUES(2, 'The Endless', 2017, FALSE, 'https://www.rottentomatoes.com/m/the_endless', 92);
INSERT INTO "PUBLIC"."MOVIE" VALUES(3, 'Timecrimes', 2007, TRUE, 'https://www.rottentomatoes.com/m/time_crimes', 90);
INSERT INTO "PUBLIC"."MOVIE" VALUES(4, 'Ad Astra', 2019, TRUE, 'https://www.rottentomatoes.com/m/ad_astra', 83);
INSERT INTO "PUBLIC"."MOVIE" VALUES(5, 'Westworld', 1973, FALSE, 'https://www.rottentomatoes.com/m/westworld', 85);
INSERT INTO "PUBLIC"."MOVIE" VALUES(6, 'High Life', 2018, FALSE, 'https://www.rottentomatoes.com/m/high_life_2019', 82);
INSERT INTO "PUBLIC"."MOVIE" VALUES(7, 'Coherence', 2013, FALSE, 'https://www.rottentomatoes.com/m/coherence_2013', 88);
INSERT INTO "PUBLIC"."MOVIE" VALUES(8, 'The Rocky Horror Picture Show', 1975, FALSE, 'https://www.rottentomatoes.com/m/rocky_horror_picture_show', 79);
INSERT INTO "PUBLIC"."MOVIE" VALUES(9, 'Midnight Special', 2016, TRUE, 'https://www.rottentomatoes.com/m/midnight_special_2015', 83);
INSERT INTO "PUBLIC"."MOVIE" VALUES(10, 'Wizards', 1977, FALSE, 'https://www.rottentomatoes.com/m/wizards', 62);
INSERT INTO "PUBLIC"."MOVIE" VALUES(11, 'Annihilation', 2018, TRUE, 'https://www.rottentomatoes.com/m/annihilation', 88);
INSERT INTO "PUBLIC"."MOVIE" VALUES(12, 'Contact', 1997, FALSE, 'https://www.rottentomatoes.com/m/1078021-contact', 68);
INSERT INTO "PUBLIC"."MOVIE" VALUES(13, 'The Congress', 2013, FALSE, 'https://www.rottentomatoes.com/m/the_congress', 73);
INSERT INTO "PUBLIC"."MOVIE" VALUES(14, 'Flight of the Navigator', 1986, FALSE, 'https://www.rottentomatoes.com/m/flight_of_the_navigator', 84);
INSERT INTO "PUBLIC"."MOVIE" VALUES(15, 'Little Shop of Horrors', 1986, FALSE, 'https://www.rottentomatoes.com/m/1012515-little_shop_of_horrors', 90);
INSERT INTO "PUBLIC"."MOVIE" VALUES(16, 'Alita: Battle Angel', 2019, TRUE, 'https://www.rottentomatoes.com/m/alita_battle_angel', 61);
INSERT INTO "PUBLIC"."MOVIE" VALUES(17, 'Ready Player One', 2018, TRUE, 'https://www.rottentomatoes.com/m/ready_player_one', 72);
INSERT INTO "PUBLIC"."MOVIE" VALUES(18, 'Plan 9 From Outer Space', 1959, FALSE, 'https://www.rottentomatoes.com/m/plan-9-from-outer-space', 66);
INSERT INTO "PUBLIC"."MOVIE" VALUES(19, 'Rollerball', 1975, FALSE, 'https://www.rottentomatoes.com/m/rollerball', 69);
INSERT INTO "PUBLIC"."MOVIE" VALUES(20, 'Silent Running', 1972, FALSE, 'https://www.rottentomatoes.com/m/silent_running', 71);
INSERT INTO "PUBLIC"."MOVIE" VALUES(21, 'War of the Worlds', 2005, TRUE, 'https://www.rottentomatoes.com/m/war_of_the_worlds', 75);
INSERT INTO "PUBLIC"."MOVIE" VALUES(22, 'Metropolis', 2001, FALSE, 'https://www.rottentomatoes.com/m/metropolis_2002', 87);
INSERT INTO "PUBLIC"."MOVIE" VALUES(23, 'Shin Godzilla', 2016, FALSE, 'https://www.rottentomatoes.com/m/godzilla_resurgence', 86);
INSERT INTO "PUBLIC"."MOVIE" VALUES(24, 'Star Trek III: The Search for Spock', 1984, TRUE, 'https://www.rottentomatoes.com/m/star_trek_iii_the_search_for_spock', 78);
INSERT INTO "PUBLIC"."MOVIE" VALUES(25, 'Rogue One: A Star Wars Story', 2016, TRUE, 'https://www.rottentomatoes.com/m/rogue_one_a_star_wars_story', 84);
INSERT INTO "PUBLIC"."MOVIE" VALUES(26, 'The Fountain', 2006, FALSE, 'https://www.rottentomatoes.com/m/the_fountain', 52);
INSERT INTO "PUBLIC"."MOVIE" VALUES(27, 'Logan''s Run', 1976, FALSE, 'https://www.rottentomatoes.com/m/logans_run', 62);
INSERT INTO "PUBLIC"."MOVIE" VALUES(28, 'The Blob', 1958, FALSE, 'https://www.rottentomatoes.com/m/the_blob', 68);
INSERT INTO "PUBLIC"."MOVIE" VALUES(29, 'Scanners', 1981, FALSE, 'https://www.rottentomatoes.com/m/1018315-scanners', 70);
INSERT INTO "PUBLIC"."MOVIE" VALUES(30, 'Things to Come', 1936, FALSE, 'https://www.rottentomatoes.com/m/things_to_come', 91);
INSERT INTO "PUBLIC"."MOVIE" VALUES(31, 'Cube', 1997, FALSE, 'https://www.rottentomatoes.com/m/cube', 64);
INSERT INTO "PUBLIC"."MOVIE" VALUES(32, 'Strange Days', 1995, FALSE, 'https://www.rottentomatoes.com/m/strange_days', 67);
INSERT INTO "PUBLIC"."MOVIE" VALUES(33, 'Heavy Metal', 1981, FALSE, 'https://www.rottentomatoes.com/m/1068461-heavy_metal', 66);
INSERT INTO "PUBLIC"."MOVIE" VALUES(34, 'A Boy and His Dog', 1975, FALSE, 'https://www.rottentomatoes.com/m/boy_and_his_dog', 78);
INSERT INTO "PUBLIC"."MOVIE" VALUES(35, 'A.I.: Artificial Intelligence', 2001, TRUE, 'https://www.rottentomatoes.com/m/ai_artificial_intelligence', 75);
INSERT INTO "PUBLIC"."MOVIE" VALUES(36, 'The Day of the Triffids', 1963, FALSE, 'https://www.rottentomatoes.com/m/the_day_of_the_triffids_1963', 77);
INSERT INTO "PUBLIC"."MOVIE" VALUES(37, 'When Worlds Collide', 1951, FALSE, 'https://www.rottentomatoes.com/m/when_worlds_collide', 81);
INSERT INTO "PUBLIC"."MOVIE" VALUES(38, 'Sunshine', 2007, TRUE, 'https://www.rottentomatoes.com/m/sunshine', 76);
INSERT INTO "PUBLIC"."MOVIE" VALUES(39, 'Liquid Sky', 1982, FALSE, 'https://www.rottentomatoes.com/m/liquid_sky', 93);
INSERT INTO "PUBLIC"."MOVIE" VALUES(40, 'Dark Star', 1974, FALSE, 'https://www.rottentomatoes.com/m/dark_star', 77);
INSERT INTO "PUBLIC"."MOVIE" VALUES(41, 'Open Your Eyes', 1997, FALSE, 'https://www.rottentomatoes.com/m/open_your_eyes_1999', 87);
INSERT INTO "PUBLIC"."MOVIE" VALUES(42, 'Paprika', 2006, TRUE, 'https://www.rottentomatoes.com/m/paprika', 85);
INSERT INTO "PUBLIC"."MOVIE" VALUES(43, 'Serenity', 2005, TRUE, 'https://www.rottentomatoes.com/m/serenity', 82);
INSERT INTO "PUBLIC"."MOVIE" VALUES(44, 'Turbo Kid', 2015, FALSE, 'https://www.rottentomatoes.com/m/turbo_kid', 91);
INSERT INTO "PUBLIC"."MOVIE" VALUES(45, 'THX-1138', 1971, FALSE, 'https://www.rottentomatoes.com/m/thx_1138', 86);
INSERT INTO "PUBLIC"."MOVIE" VALUES(46, 'Attack the Block', 2011, TRUE, 'https://www.rottentomatoes.com/m/attack_the_block', 90);
INSERT INTO "PUBLIC"."MOVIE" VALUES(47, 'Upgrade', 2018, FALSE, 'https://www.rottentomatoes.com/m/upgrade_2018', 88);
INSERT INTO "PUBLIC"."MOVIE" VALUES(48, 'Star Trek: First Contact', 1996, FALSE, 'https://www.rottentomatoes.com/m/star_trek_first_contact', 92);
INSERT INTO "PUBLIC"."MOVIE" VALUES(49, 'The World''s End', 2013, TRUE, 'https://www.rottentomatoes.com/m/the_worlds_end', 89);
INSERT INTO "PUBLIC"."MOVIE" VALUES(50, 'Invasion of the Body Snatchers', 1978, FALSE, 'https://www.rottentomatoes.com/m/1010679-invasion_of_the_body_snatchers', 92);
INSERT INTO "PUBLIC"."MOVIE" VALUES(51, 'The Host', 2006, TRUE, 'https://www.rottentomatoes.com/m/the_host_2007', 93);
INSERT INTO "PUBLIC"."MOVIE" VALUES(52, 'A Quiet Place', 2018, FALSE, 'https://www.rottentomatoes.com/m/a_quiet_place_2018', 96);
INSERT INTO "PUBLIC"."MOVIE" VALUES(53, 'Star Wars: The Force Awakens', 2015, TRUE, 'https://www.rottentomatoes.com/m/star_wars_episode_vii_the_force_awakens', 93);
INSERT INTO "PUBLIC"."MOVIE" VALUES(54, 'Repo Man', 1984, TRUE, 'https://www.rottentomatoes.com/m/repo_man', 98);
INSERT INTO "PUBLIC"."MOVIE" VALUES(55, 'Starship Troopers', 1997, TRUE, 'https://www.rottentomatoes.com/m/starship_troopers', 70);
INSERT INTO "PUBLIC"."MOVIE" VALUES(56, 'The Fifth Element', 1997, TRUE, 'https://www.rottentomatoes.com/m/fifth_element', 71);
INSERT INTO "PUBLIC"."MOVIE" VALUES(57, 'V for Vendetta', 2006, TRUE, 'https://www.rottentomatoes.com/m/v_for_vendetta', 73);
INSERT INTO "PUBLIC"."MOVIE" VALUES(58, 'Dredd', 2012, TRUE, 'https://www.rottentomatoes.com/m/dredd', 79);
INSERT INTO "PUBLIC"."MOVIE" VALUES(59, 'The Brother From Another Planet', 1984, FALSE, 'https://www.rottentomatoes.com/m/the_brother_from_another_planet', 89);
INSERT INTO "PUBLIC"."MOVIE" VALUES(60, 'The Adventures of Buckaroo Banzai Across the Eighth Dimension', 1984, FALSE, 'https://www.rottentomatoes.com/m/the_adventures_of_buckaroo_banzai', 66);
INSERT INTO "PUBLIC"."MOVIE" VALUES(61, 'Dark City', 1998, TRUE, 'https://www.rottentomatoes.com/m/dark_city', 75);
INSERT INTO "PUBLIC"."MOVIE" VALUES(62, 'Under the Skin', 2013, FALSE, 'https://www.rottentomatoes.com/m/under_the_skin_2013', 84);
INSERT INTO "PUBLIC"."MOVIE" VALUES(63, 'The Man Who Fell to Earth', 1976, FALSE, 'https://www.rottentomatoes.com/m/man_who_fell_to_earth', 82);
INSERT INTO "PUBLIC"."MOVIE" VALUES(64, 'The Fly', 1986, FALSE, 'https://www.rottentomatoes.com/m/1007602-fly', 93);
INSERT INTO "PUBLIC"."MOVIE" VALUES(65, 'Cloverfield', 2008, TRUE, 'https://www.rottentomatoes.com/m/cloverfield', 78);
INSERT INTO "PUBLIC"."MOVIE" VALUES(66, 'Men in Black', 1997, TRUE, 'https://www.rottentomatoes.com/m/men_in_black', 91);
INSERT INTO "PUBLIC"."MOVIE" VALUES(67, 'Tron', 1982, TRUE, 'https://www.rottentomatoes.com/m/tron', 72);
INSERT INTO "PUBLIC"."MOVIE" VALUES(68, 'Bumblebee', 2018, TRUE, 'https://www.rottentomatoes.com/m/bumblebee', 91);
INSERT INTO "PUBLIC"."MOVIE" VALUES(69, 'Independence Day', 1996, TRUE, 'https://www.rottentomatoes.com/m/1071806-independence_day', 68);
INSERT INTO "PUBLIC"."MOVIE" VALUES(70, 'Barbarella', 1968, FALSE, 'https://www.rottentomatoes.com/m/barbarella', 74);
INSERT INTO "PUBLIC"."MOVIE" VALUES(71, 'Donnie Darko', 2001, TRUE, 'https://www.rottentomatoes.com/m/donnie_darko', 87);
INSERT INTO "PUBLIC"."MOVIE" VALUES(72, 'Pacific Rim', 2013, TRUE, 'https://www.rottentomatoes.com/m/pacific_rim_2013', 72);
INSERT INTO "PUBLIC"."MOVIE" VALUES(73, 'Idiocracy', 2006, TRUE, 'https://www.rottentomatoes.com/m/idiocracy', 71);
INSERT INTO "PUBLIC"."MOVIE" VALUES(74, 'Fahrenheit 451', 1966, FALSE, 'https://www.rottentomatoes.com/m/1007003-fahrenheit_451', 81);
INSERT INTO "PUBLIC"."MOVIE" VALUES(75, 'Demolition Man', 1993, FALSE, 'https://www.rottentomatoes.com/m/demolition_man', 62);
INSERT INTO "PUBLIC"."MOVIE" VALUES(76, 'A Scanner Darkly', 2006, TRUE, 'https://www.rottentomatoes.com/m/scanner_darkly', 68);
INSERT INTO "PUBLIC"."MOVIE" VALUES(77, 'Source Code', 2011, TRUE, 'https://www.rottentomatoes.com/m/source_code', 92);
INSERT INTO "PUBLIC"."MOVIE" VALUES(78, 'The Abyss', 1989, FALSE, 'https://www.rottentomatoes.com/m/abyss', 88);
INSERT INTO "PUBLIC"."MOVIE" VALUES(79, 'Rise of the Planet of the Apes', 2011, TRUE, 'https://www.rottentomatoes.com/m/rise_of_the_planet_of_the_apes', 82);
INSERT INTO "PUBLIC"."MOVIE" VALUES(80, 'Altered States', 1980, FALSE, 'https://www.rottentomatoes.com/m/altered_states', 85);
INSERT INTO "PUBLIC"."MOVIE" VALUES(81, 'Predestination', 2014, TRUE, 'https://www.rottentomatoes.com/m/predestination', 84);
INSERT INTO "PUBLIC"."MOVIE" VALUES(82, 'They Live', 1988, FALSE, 'https://www.rottentomatoes.com/m/they_live', 85);
INSERT INTO "PUBLIC"."MOVIE" VALUES(83, 'Seconds', 1966, FALSE, 'https://www.rottentomatoes.com/m/seconds', 79);
INSERT INTO "PUBLIC"."MOVIE" VALUES(84, 'Soylent Green', 1973, FALSE, 'https://www.rottentomatoes.com/m/soylent_green', 69);
INSERT INTO "PUBLIC"."MOVIE" VALUES(85, '20,000 Leagues Under the Sea', 1954, TRUE, 'https://www.rottentomatoes.com/m/1000079-20000_leagues_under_the_sea', 90);
INSERT INTO "PUBLIC"."MOVIE" VALUES(86, 'The Hunger Games', 2012, TRUE, 'https://www.rottentomatoes.com/m/the_hunger_games', 84);
INSERT INTO "PUBLIC"."MOVIE" VALUES(87, 'Avatar', 2009, TRUE, 'https://www.rottentomatoes.com/m/avatar', 82);
INSERT INTO "PUBLIC"."MOVIE" VALUES(88, 'Minority Report', 2002, TRUE, 'https://www.rottentomatoes.com/m/minority_report', 90);
INSERT INTO "PUBLIC"."MOVIE" VALUES(89, 'Alphaville', 1965, FALSE, 'https://www.rottentomatoes.com/m/alphaville', 91);
INSERT INTO "PUBLIC"."MOVIE" VALUES(90, 'Them!', 1954, FALSE, 'https://www.rottentomatoes.com/m/1021186-them', 93);
INSERT INTO "PUBLIC"."MOVIE" VALUES(91, 'Videodrome', 1983, FALSE, 'https://www.rottentomatoes.com/m/videodrome', 80);
INSERT INTO "PUBLIC"."MOVIE" VALUES(92, 'Snowpiercer', 2013, TRUE, 'https://www.rottentomatoes.com/m/snowpiercer', 94);
INSERT INTO "PUBLIC"."MOVIE" VALUES(93, 'Invasion of the Body Snatchers', 1956, FALSE, 'https://www.rottentomatoes.com/m/1010678-invasion_of_the_body_snatchers', 98);
INSERT INTO "PUBLIC"."MOVIE" VALUES(94, 'Predator', 1987, FALSE, 'https://www.rottentomatoes.com/m/predator', 80);
INSERT INTO "PUBLIC"."MOVIE" VALUES(95, 'Planet of the Apes', 1968, TRUE, 'https://www.rottentomatoes.com/m/1016397-planet_of_the_apes', 87);
INSERT INTO "PUBLIC"."MOVIE" VALUES(96, 'Mad Max 2: The Road Warrior', 1981, TRUE, 'https://www.rottentomatoes.com/m/mad_max_2_the_road_warrior', 95);
INSERT INTO "PUBLIC"."MOVIE" VALUES(97, 'Star Trek', 2009, TRUE, 'https://www.rottentomatoes.com/m/star_trek_11', 94);
INSERT INTO "PUBLIC"."MOVIE" VALUES(98, 'Escape From New York', 1981, FALSE, 'https://www.rottentomatoes.com/m/1006717-escape_from_new_york', 86);
INSERT INTO "PUBLIC"."MOVIE" VALUES(99, 'The War of the Worlds', 1953, FALSE, 'https://www.rottentomatoes.com/m/the_war_of_the_worlds', 89);
INSERT INTO "PUBLIC"."MOVIE" VALUES(100, 'Blade Runner 2049', 2017, TRUE, 'https://www.rottentomatoes.com/m/blade_runner_2049', 88);
INSERT INTO "PUBLIC"."MOVIE" VALUES(101, 'Galaxy Quest', 1999, TRUE, 'https://www.rottentomatoes.com/m/galaxy_quest', 90);
INSERT INTO "PUBLIC"."MOVIE" VALUES(102, 'Fantastic Voyage', 1966, FALSE, 'https://www.rottentomatoes.com/m/fantastic_voyage', 91);
INSERT INTO "PUBLIC"."MOVIE" VALUES(103, 'Solaris', 1972, TRUE, 'https://www.rottentomatoes.com/m/solaris_1976', 92);
INSERT INTO "PUBLIC"."MOVIE" VALUES(104, 'Her', 2013, TRUE, 'https://www.rottentomatoes.com/m/her', 94);
INSERT INTO "PUBLIC"."MOVIE" VALUES(105, 'The Iron Giant', 1999, TRUE, 'https://www.rottentomatoes.com/m/iron_giant', 96);
INSERT INTO "PUBLIC"."MOVIE" VALUES(106, 'Fantastic Planet', 1973, TRUE, 'https://www.rottentomatoes.com/m/fantastic_planet', 91);
INSERT INTO "PUBLIC"."MOVIE" VALUES(107, 'Total Recall', 1990, TRUE, 'https://www.rottentomatoes.com/m/total_recall', 83);
INSERT INTO "PUBLIC"."MOVIE" VALUES(108, 'Moon', 2009, TRUE, 'https://www.rottentomatoes.com/m/moon', 90);
INSERT INTO "PUBLIC"."MOVIE" VALUES(109, 'The Martian', 2015, TRUE, 'https://www.rottentomatoes.com/m/the_martian', 91);
INSERT INTO "PUBLIC"."MOVIE" VALUES(110, 'Gravity', 2013, TRUE, 'https://www.rottentomatoes.com/m/gravity_2013', 96);
INSERT INTO "PUBLIC"."MOVIE" VALUES(111, 'Interstellar', 2014, TRUE, 'https://www.rottentomatoes.com/m/interstellar_2014', 73);
INSERT INTO "PUBLIC"."MOVIE" VALUES(112, 'Eternal Sunshine of the Spotless Mind', 2004, TRUE, 'https://www.rottentomatoes.com/m/eternal_sunshine_of_the_spotless_mind', 92);
INSERT INTO "PUBLIC"."MOVIE" VALUES(113, 'Looper', 2012, TRUE, 'https://www.rottentomatoes.com/m/looper', 93);
INSERT INTO "PUBLIC"."MOVIE" VALUES(114, 'Close Encounters of the Third Kind', 1977, TRUE, 'https://www.rottentomatoes.com/m/close_encounters_of_the_third_kind', 94);
INSERT INTO "PUBLIC"."MOVIE" VALUES(115, 'Arrival', 2016, TRUE, 'https://www.rottentomatoes.com/m/arrival_2016', 94);
INSERT INTO "PUBLIC"."MOVIE" VALUES(116, 'Ex Machina', 2014, TRUE, 'https://www.rottentomatoes.com/m/ex_machina', 92);
INSERT INTO "PUBLIC"."MOVIE" VALUES(117, 'WALL-E', 2008, TRUE, 'https://www.rottentomatoes.com/m/wall_e', 95);
INSERT INTO "PUBLIC"."MOVIE" VALUES(118, 'E.T. the Extra-Terrestrial', 1982, FALSE, 'https://www.rottentomatoes.com/m/et_the_extraterrestrial', 99);
INSERT INTO "PUBLIC"."MOVIE" VALUES(119, 'Godzilla', 1954, FALSE, 'https://www.rottentomatoes.com/m/godzilla_1956', 93);
INSERT INTO "PUBLIC"."MOVIE" VALUES(120, 'Forbidden Planet', 1956, FALSE, 'https://www.rottentomatoes.com/m/forbidden_planet', 96);
INSERT INTO "PUBLIC"."MOVIE" VALUES(121, '12 Monkeys', 1995, FALSE, 'https://www.rottentomatoes.com/m/12_monkeys', 88);
INSERT INTO "PUBLIC"."MOVIE" VALUES(122, 'Jurassic Park', 1993, FALSE, 'https://www.rottentomatoes.com/m/jurassic_park', 91);
INSERT INTO "PUBLIC"."MOVIE" VALUES(123, 'Primer', 2004, TRUE, 'https://www.rottentomatoes.com/m/primer', 73);
INSERT INTO "PUBLIC"."MOVIE" VALUES(124, 'Stalker', 1979, FALSE, 'https://www.rottentomatoes.com/m/1043378-stalker', 10);
INSERT INTO "PUBLIC"."MOVIE" VALUES(125, 'Gattaca', 1997, TRUE, 'https://www.rottentomatoes.com/m/gattaca', 82);
INSERT INTO "PUBLIC"."MOVIE" VALUES(126, 'Ghost in the Shell', 1995, TRUE, 'https://www.rottentomatoes.com/m/ghost_in_the_shell', 95);
INSERT INTO "PUBLIC"."MOVIE" VALUES(127, 'Brazil', 1985, TRUE, 'https://www.rottentomatoes.com/m/1003033-brazil', 98);
INSERT INTO "PUBLIC"."MOVIE" VALUES(128, 'Star Trek II: The Wrath of Khan', 1982, TRUE, 'https://www.rottentomatoes.com/m/star_trek_ii_the_wrath_of_khan', 86);
INSERT INTO "PUBLIC"."MOVIE" VALUES(129, 'District 9', 2009, TRUE, 'https://www.rottentomatoes.com/m/district_9', 90);
INSERT INTO "PUBLIC"."MOVIE" VALUES(130, 'A Clockwork Orange', 1971, TRUE, 'https://www.rottentomatoes.com/m/clockwork_orange', 88);
INSERT INTO "PUBLIC"."MOVIE" VALUES(131, 'RoboCop', 1987, TRUE, 'https://www.rottentomatoes.com/m/1017712-robocop', 91);
INSERT INTO "PUBLIC"."MOVIE" VALUES(132, 'The Day the Earth Stood Still', 1951, FALSE, 'https://www.rottentomatoes.com/m/1005371-day_the_earth_stood_still', 95);
INSERT INTO "PUBLIC"."MOVIE" VALUES(133, 'Akira', 1988, TRUE, 'https://www.rottentomatoes.com/m/akira', 91);
INSERT INTO "PUBLIC"."MOVIE" VALUES(134, 'Children of Men', 2006, TRUE, 'https://www.rottentomatoes.com/m/children_of_men', 92);
INSERT INTO "PUBLIC"."MOVIE" VALUES(135, 'The Terminator', 1984, TRUE, 'https://www.rottentomatoes.com/m/terminator', 10);
INSERT INTO "PUBLIC"."MOVIE" VALUES(136, 'Edge of Tomorrow', 2014, TRUE, 'https://www.rottentomatoes.com/m/live_die_repeat_edge_of_tomorrow', 91);
INSERT INTO "PUBLIC"."MOVIE" VALUES(137, 'Aliens', 1986, TRUE, 'https://www.rottentomatoes.com/m/1000617-aliens', 98);
INSERT INTO "PUBLIC"."MOVIE" VALUES(138, 'Star Wars: Episode V -- The Empire Strikes Back', 1980, TRUE, 'https://www.rottentomatoes.com/m/star_wars_the_empire_strikes_back', 94);
INSERT INTO "PUBLIC"."MOVIE" VALUES(139, 'The Thing', 1982, TRUE, 'https://www.rottentomatoes.com/m/1021244-thing', 84);
INSERT INTO "PUBLIC"."MOVIE" VALUES(140, 'Mad Max: Fury Road', 2015, TRUE, 'https://www.rottentomatoes.com/m/mad_max_fury_road', 97);
INSERT INTO "PUBLIC"."MOVIE" VALUES(141, 'Alien', 1979, TRUE, 'https://www.rottentomatoes.com/m/alien', 98);
INSERT INTO "PUBLIC"."MOVIE" VALUES(142, 'Terminator 2: Judgment Day', 1991, TRUE, 'https://www.rottentomatoes.com/m/terminator_2_judgment_day', 92);
INSERT INTO "PUBLIC"."MOVIE" VALUES(143, 'Inception', 2010, TRUE, 'https://www.rottentomatoes.com/m/inception', 87);
INSERT INTO "PUBLIC"."MOVIE" VALUES(144, 'The Matrix', 1999, TRUE, 'https://www.rottentomatoes.com/m/matrix', 88);
INSERT INTO "PUBLIC"."MOVIE" VALUES(145, 'Star Wars: Episode IV -- A New Hope', 1977, TRUE, 'https://www.rottentomatoes.com/m/star_wars_a_new_hope', 93);
INSERT INTO "PUBLIC"."MOVIE" VALUES(146, 'Metropolis', 1927, TRUE, 'https://www.rottentomatoes.com/m/1013775-metropolis', 97);
INSERT INTO "PUBLIC"."MOVIE" VALUES(147, 'Blade Runner', 1982, TRUE, 'https://www.rottentomatoes.com/m/blade_runner', 89);
INSERT INTO "PUBLIC"."MOVIE" VALUES(148, 'Back to the Future', 1985, TRUE, 'https://www.rottentomatoes.com/m/back_to_the_future', 97);
INSERT INTO "PUBLIC"."MOVIE" VALUES(149, '2001: A Space Odyssey', 1968, TRUE, 'https://www.rottentomatoes.com/m/2001_a_space_odyssey', 91);
