CREATE TABLE IF NOT EXISTS MOVIE (
    "ID"   INTEGER      NOT NULL AUTO_INCREMENT,
    "TITLE" VARCHAR(128) NOT NULL,
    "YEAR" INTEGER NOT NULL,
    "SEEN" boolean NOT NULL DEFAULT false,
    "URL" VARCHAR(255) NOT NULL,
    "TOMATOES" INTEGER NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT UC_MOVIE_TITLE_YEAR UNIQUE ("TITLE", "YEAR")
);
